spring.application.name = dart game

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60
spring.datasource.url=jdbc:postgresql://localhost:5432/dartgame
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
